recipe: lamp
name: .yxorp
config:
  php: '8.0'
  webroot: .
  xdebug: true
services:
  memcached:
    type: memcached:1.5.11
  appserver:
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
  mysql:
    type: mysql
    # https://docs.lando.dev/config/services.html#service-url-scanning
    scanner: false
    overrides:
      entrypoint: 'echo disabled service'
      restart: no
