<?php
return [
    'name' => 'sites',
    'label' => 'sites',
    'info' => '',
    'type' => 'collection',
    'fields' => [
        0 => [
            'name' => 'host',
            'label' => 'host',
            'type' => 'text',
            'default' => '',
            'info' => 'The host name of the website, such as "sample.com," leaving off the sub-domain and the www prefix because these are both automatically generated.',
            'group' => 'urls',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-3',
            'lst' => true,
            'acl' => [
            ],
            'required' => true,
            'meta' => NULL,
        ],
        1 => [
            'name' => 'target',
            'label' => 'target',
            'type' => 'text',
            'default' => '',
            'info' => 'The hostname of the website that you want to proxy, such as "example.com," excluding the subdomain and the www prefix, both of which will be automatically generated by the system.',
            'group' => 'urls',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-3',
            'lst' => true,
            'acl' => [
            ],
            'required' => true,
            'meta' => NULL,
        ],
        2 => [
            'name' => 'affiliate',
            'label' => 'affiliate',
            'type' => 'text',
            'default' => '',
            'info' => 'If you wish to append the affiliate ID to the fetch URL, such as "affiliate id=xxxx", omit characters that will be produced automatically later, such as the question mark (?) and the ampersand (&).',
            'group' => 'affiliate',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-3',
            'lst' => true,
            'acl' => [
            ],
            'meta' => NULL,
        ],
        3 => [
            'name' => 'plugins',
            'label' => 'plugins',
            'type' => 'select',
            'default' => '',
            'info' => 'Activate any site plugins that you\'d like, which you may find under the directory called "/plugin" if you look for them there.',
            'group' => 'plugins',
            'localize' => 0,
            'options' => [
            ],
            'width' => '1-3',
            'lst' => true,
            'acl' => [
            ],
            'opts' => [
                'multiple' => true,
                'options' => [
                    0 => 'BlockListPlugin',
                    1 => 'CookiePlugin',
                    2 => 'DailyMotionPlugin',
                    3 => 'HeaderRewritePlugin',
                    4 => ' LogPlugin',
                    5 => 'ProxifyPlugin',
                    6 => 'StreamPlugin',
                    7 => 'TwitterPlugin',
                    8 => 'YoutubePlugin',
                    9 => 'spinPlugin',
                ],
            ],
            'meta' => NULL,
        ],
        4 => [
            'name' => 'link',
            'type' => 'color',
            'label' => 'link',
            'info' => 'Make adjustments to the color of the hyperlinks. (This will be applied to all hyperlinks on the page)',
            'group' => 'link',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        5 => [
            'name' => 'linkvisited',
            'type' => 'color',
            'label' => 'link',
            'info' => 'Modify the color of the links that have already been clicked on. [a:visted]',
            'group' => 'link',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        6 => [
            'name' => 'linkhover',
            'type' => 'color',
            'label' => 'link',
            'info' => 'Change the color of the link when the mouse is dragged over it (using the a:hover attribute).',
            'group' => 'link',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        7 => [
            'name' => 'button',
            'type' => 'color',
            'label' => 'button',
            'info' => 'You are able to change the color of the buttons often seen on forms, such as the search and contact forms.',
            'group' => 'button',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        8 => [
            'name' => 'buttonhover',
            'type' => 'color',
            'label' => 'button',
            'info' => 'Change the color of the button while hovering over [button:hover].',
            'group' => 'button',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        9 => [
            'name' => 'bgcolor',
            'type' => 'color',
            'label' => 'bg',
            'info' => 'You may make the website backdrop a color of your choosing by using this setting. (Additional styling should be handled with the custom CSS)',
            'group' => 'background',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'size' => '40',
            ],
        ],
        10 => [
            'name' => 'background',
            'type' => 'asset',
            'label' => 'bg:img',
            'info' => 'Here you have the ability to use a photo of your choosing as the background of the website (Any custom positioning can be done in the css)',
            'group' => 'background',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
            ],
        ],
        11 => [
            'name' => 'logo',
            'type' => 'asset',
            'label' => 'logo',
            'info' => 'logo needs to be manually inserted',
            'group' => 'logo',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
            ],
        ],
        12 => [
            'name' => 'header',
            'type' => 'boolean',
            'label' => 'head',
            'info' => 'Show/hide the header / banner section at the top of the website (If a custom header is added below, this option will be ignored and the custom header will be used to replace the header)',
            'group' => 'head',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'default' => true,
            ],
        ],
        13 => [
            'name' => 'htmlhead',
            'label' => 'head:custom',
            'type' => 'wysiwyg',
            'default' => '',
            'info' => 'Replace existing header with a custom header (Overrides show/hide option above)',
            'group' => 'head',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-1',
            'lst' => true,
            'acl' => [
            ],
            'opts' => NULL,
            'meta' => NULL,
        ],
        14 => [
            'name' => 'menu',
            'type' => 'boolean',
            'label' => 'nav',
            'info' => 'Show/hide the primary navigation menu (If a nav is added below, this option will be ignored and the custom nav will be used to replace the primary nav)',
            'group' => 'menu',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'default' => true,
            ],
        ],
        15 => [
            'name' => 'htmlmenu',
            'type' => 'wysiwyg',
            'label' => 'nav:custom',
            'info' => 'Replace existing menu with a custom menu (Overrides show/hide option above)',
            'group' => 'menu',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
            ],
        ],
        16 => [
            'name' => 'footer',
            'type' => 'boolean',
            'label' => 'foot',
            'info' => 'Show/hide the footer area at the very bottom of the website. (If a custom header is added below, this option will be ignored and the custom footer will be used to replace the footer.)',
            'group' => 'footer',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
                'default' => true,
            ],
        ],
        17 => [
            'name' => 'htmlfoot',
            'type' => 'wysiwyg',
            'label' => 'foot:custom',
            'info' => 'Replace existing footer with a custom footer (Overrides show/hide option above)',
            'group' => 'footer',
            'i18n' => false,
            'required' => false,
            'multiple' => false,
            'meta' => [
            ],
            'opts' => [
            ],
        ],
        18 => [
            'name' => 'css',
            'label' => 'css',
            'type' => 'code',
            'default' => '',
            'info' => 'Make advantage of this space so that you may bring in your own custom CSS styles (excl. <style> tags)',
            'group' => 'styling',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-2',
            'lst' => true,
            'acl' => [
            ],
            'meta' => NULL,
        ],
        19 => [
            'name' => 'js',
            'label' => 'js',
            'type' => 'code',
            'default' => '',
            'info' => 'You may customize the page by adding some of your own unique Javascript to it (excl. <sciprt> tags)',
            'group' => 'javascript',
            'localize' => false,
            'options' => [
            ],
            'width' => '1-2',
            'lst' => true,
            'acl' => [
            ],
            'meta' => NULL,
        ],
        20 => [
            'name' => 'replace',
            'label' => 'replace',
            'type' => 'object',
            'default' => '',
            'info' => 'If you use a key value pair, the key will be replaced with the value once it has been located i.e: {  "search": "replace" }',
            'group' => 'replace',
            'localize' => false,
            'options' => [
                'search' => 'replace',
            ],
            'width' => '1-2',
            'lst' => true,
            'acl' => [
            ],
            'opts' => [
                'height' => NULL,
            ],
            'meta' => NULL,
        ],
        21 => [
            'name' => 'pattern',
            'label' => 'pattern',
            'type' => 'object',
            'default' => '',
            'info' => 'The regular expression pattern search looks for a pattern, and then it utilizes another pattern to modify the specific value; in order to do this, there must be a key value pair present i.e. {"\'<header[\\s\\S]*?header>\'","<footer$1footer>"}',
            'group' => 'replace',
            'localize' => false,
            'options' => [
                'search' => 'replace',
            ],
            'width' => '1-2',
            'lst' => true,
            'acl' => [
            ],
            'opts' => [
                'height' => NULL,
            ],
            'meta' => NULL,
        ],
    ],
    'sortable' => false,
    'in_menu' => 0,
    '_created' => 1658962514,
    '_modified' => 1659780694,
    'color' => '#00ffb3',
    'acl' => [
    ],
    'sort' => [
        'column' => '_created',
        'dir' => -1,
    ],
    'rules' => [
        'create' => [
            'enabled' => 0,
        ],
        'read' => [
            'enabled' => true,
        ],
        'update' => [
            'enabled' => 0,
        ],
        'delete' => [
            'enabled' => 0,
        ],
    ],
    'preview' => [
        0 => [
            'name' => 'host',
            'uri' => 'https://www.obeyi.com',
        ],
    ],
    'group' => 'core',
    'revisions' => false,
];
