version = 1

exclude_patterns = [
  "/lib/vendor/**",
  "/modules/App/assets/vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]