<?php
define('CACHE_FIX', ['GuzzleHttp\Psr7\Response::__set_state', 'ArrayObject::__set_state', 'Bugsnag\Breadcrumbs\Recorder::__set_state', 'Bugsnag\Callbacks\GlobalMetaData::__set_state', 'Bugsnag\Callbacks\RequestContext::__set_state', 'Bugsnag\Callbacks\RequestMetaData::__set_state', 'Bugsnag\Callbacks\RequestSession::__set_state', 'Bugsnag\Callbacks\RequestUser::__set_state', 'Bugsnag\Client::__set_state', 'Bugsnag\Configuration::__set_state', 'Bugsnag\HttpClient::__set_state', 'Bugsnag\Internal\FeatureFlagDelegate::__set_state', 'Bugsnag\Middleware\BreadcrumbData::__set_state', 'Bugsnag\Middleware\CallbackBridge::__set_state', 'Bugsnag\Middleware\DiscardClasses::__set_state', 'Bugsnag\Middleware\NotificationSkipper::__set_state', 'Bugsnag\Middleware\SessionData::__set_state', 'Bugsnag\Pipeline::__set_state', 'Bugsnag\Request\BasicResolver::__set_state', 'Bugsnag\SessionTracker::__set_state', 'Closure::__set_state', 'GuzzleHttp\Client::__set_state', 'GuzzleHttp\Cookie\CookieJar::__set_state', 'GuzzleHttp\HandlerStack::__set_state', 'GuzzleHttp\Psr7\Uri::__set_state', 'LimeExtra\App::__set_state', 'LimeExtra\Helper\I18n::__set_state', 'LimeExtra\Helper\SimpleAcl::__set_state', 'Lime\Helper\Cache::__set_state', 'Lime\Module::__set_state', 'Lime\Request::__set_state', 'stdClass::__set_state', 'yxorP\app\lib\http\paramStore::__set_state', 'yxorP\app\lib\http\request::__set_state', 'yxorP\app\lib\http\response::__set_state']);
define('YXORP_HTTP_HOST', $_SERVER['HTTP_HOST']);
define('YXORP_REQUEST_URI', $_SERVER['REQUEST_URI']);
define('CHAR_PERIOD', '.');
define('VAR_TMP', 'tmp');
define('FILE_TMP', CHAR_PERIOD . VAR_TMP);
define('DIR_TMP', VAR_TMP . DIRECTORY_SEPARATOR . urlencode(YXORP_HTTP_HOST) . DIRECTORY_SEPARATOR);
define('CACHE_KEY', rtrim(strtr(base64_encode(YXORP_REQUEST_URI), '+/=', '._-')));
define('PATH_TMP_DIR', __DIR__ . DIRECTORY_SEPARATOR . DIR_TMP);
define('PATH_TMP_FILE', __DIR__ . DIRECTORY_SEPARATOR . DIR_TMP . CACHE_KEY . FILE_TMP);
define('DIR_LIB', 'lib' . DIRECTORY_SEPARATOR);
define('CACHE_KEY_CONTEXT', rtrim(strtr(base64_encode(YXORP_HTTP_HOST), '+/=', '._-')));
define('EXT_TEXT', 'txt');
define('CHAR_SLASH', '/');
define('COOKIE_JAR', 'cookie_jar' . CHAR_PERIOD);
define('FILE_COOKIE_JAR', COOKIE_JAR . EXT_TEXT);
define('VAR_TMP_STORE', 'TMP_STORE');
define('CHAR_UNDER', '_');
define('VAR_TEXT', 'text');
define('VAR_HTML', 'html');
define('VAR_VAR', 'VAR');
define('CHAR_DASH', '-');
define('CHAR_HASH', '#');
define('CHAR_EQUALS', '=');
define('CHAR_ASTRIX', '*');
define('CHAR_EMPTY_STRING', '');
define('CHAR_PLUS', '+');
define('CHAR_SLASH_BACK', '\\');
define('CHAR_QUESTION', '?');
define('CHAR_AT', '@');
define('CHAR_CURVE', '{');
define('CHAR_CURVE_CLOSE', '}');
define('CHAR_BRACKET', '(');
define('CHAR_BRACKET_CLOSE', ')');
define('CHAR_S', 's');
define('CHAR_SQUARE', '[');
define('CHAR_SQUARE_CLOSE', ']');
define('CHAR_A', 'a');
define('CHAR_Z', 'z');
define('CHAR_0', '0');
define('CHAR_9', '9');
define('CHAR_UP', '^');
define('CHAR_USD', '$');
define('CHAR_I', 'i');
define('CHAR_COLON', ':');
define('CHAR_EXCLAMATION', '!');
define('CHAR_CAP_P', 'P');
define('CHAR_ARROW', '<');
define('CHAR_ARROW_CLOSE', '>');
define('CHAR_COMMA', ');define(');
define('CHAR_2', '2');
define('CHAR_1', '1');
define('CHAR_6', '6');
define('CHAR_3', '3');
define('NUM_ENV_LIMIT', 2);
define('EXT_JSON', CHAR_PERIOD . 'json');
define('EXT_PHP', CHAR_PERIOD . 'php');
define('EXT_ENV', CHAR_PERIOD . 'env');
define('EXT_PHAR', CHAR_PERIOD . 'phar');
define('VAR_USER', 'user');
define('VAR_NAME', 'name');
define('VAR_EMAIL', 'email');
define('VAR_PASSWORD', 'password');
define('VAR_GROUP', 'group');
define('VAR_ACTIVE', 'active');
define('VAR_COCKPIT', 'cockpit');
define('VAR_I18N', 'i18n');
define('VAR_CREATED', '_created');
define('VAR_MODIFIED', '_modified');
define('VAR_USER_IP', 'user_ip');
define('VAR_USER_IP_LONG', 'user_ip_long');
define('VAR_URL', 'url');
define('VAR_URL_HOST', 'url_host');
define('VAR_HTTPS', 'https:' . CHAR_SLASH . CHAR_SLASH);
define('VAR_HTTPS_ONLY', 'https');
define('VAR_ALLOW_REDIRECTS', 'allow_redirects');
define('VAR_HTTP_ERRORS', 'http_errors');
define('VAR_DECODE_CONTENT', 'decode_content');
define('VAR_VERIFY', 'verify');
define('VAR_COOKIES', 'cookies');
define('VAR_IDN_CONVERSION', 'idn_conversion');
define('VAR_APPLICATION_URLENCODED', 'application/x-www-form-urlencoded');
define('VAR_CONTENT_TYPE', 'content-type');
define('VAR_CONTENT_LENGTH', 'content-length');
define('VAR_TYPE', 'type');
define('VAR_ERROR', 'error');
define('VAR_TMP_NAME', 'tmp_name');
define('VAR_GET_URL', 'getUrl');
define('VAR_UCFIRST', 'ucfirst');
define('VAR_STRTOLOWER', 'strtolower');
define('VAR_HTTP', 'http:');
define('VAR_INTERFACE', 'Interface');
define('VAR_GETCSV', 'str_getcsv');
define('VAR_DOMAIN', 'domain');
define('VAR_PATTERN', 'pattern');
define('VAR_PATTERN_UP', 'PATTERN');
define('VAR_REPLACE', 'replace');
define('VAR_SERVER', 'SERVER');
define('VAR_GUZZLE', 'guzzle');
define('VAR_BUGSNAG', 'bugsnag');
define('VAR_RESPONSE', 'RESPONSE');
define('VAR_REQUEST', 'REQUEST');
define('VAR_COCKPIT_ACCOUNTS', 'accounts');
define('VAR_PLUGINS', 'plugins');
define('VAR_TARGET', 'TARGET');
define('VAR_TARGET_PATTERN', 'TARGET_PATTERN');
define('VAR_TARGET_REPLACE', 'TARGET_REPLACE');
define('VAR_SITE', 'SITE');
define('VAR_HOST', 'HOST');
define('VAR_INSTALL', 'INSTALL');
define('VAR_INC', 'INC');
define('VAR_REPLACE_UP', 'REPLACE');
define('VAR_REWRITE', 'REWRITE');
define('VAR_SEARCH', 'SEARCH');
define('VAR_FILES', 'files');
define('VAR_PHP', 'PHP');
define('VAR_SELF', 'SELF');
define('VAR_APP', 'APP');
define('VAR_NAME_UP', 'NAME');
define('VAR_URL_UP', 'URL');
define('VAR_PARSE_UP', 'PARSE');
define('VAR_URI', 'URI');
define('VAR_SUB', 'SUB');
define('VAR_DOMAIN_UP', 'DOMAIN');
define('VAR_DIR', 'DIR');
define('VAR_FULL', 'FULL');
define('VAR_HTTPS_UP', 'HTTPS');
define('VAR_HTTP_UP', 'HTTP');
define('VAR_METHOD', 'METHOD');
define('VAR_REMOTE', 'REMOTE');
define('VAR_ADDR', 'ADDR');
define('VAR_EVENT', 'EVENT');
define('VAR_MIME', 'mime');
define('VAR_TYPES', 'TYPES');
define('VAR_LIST', 'LIST');
define('VAR_GLOBAL_UP', 'GLOBAL');
define('VAR_GLOBALS', 'GLOBALS');
define('VAR_GLOBAL', 'global');
define('VAR_VALUE', 'value');
define('TARGET_DOMAIN', 'TARGET_DOMAIN');
define('SITE_DETAILS', 'SITE_DETAILS');
define('SITE_DOMAIN', 'SITE_DOMAIN');
define('SUFFIX_LIST', 'SUFFIX_LIST');
define('VAR_DASH_LOWER', CHAR_DASH . CHAR_UNDER);
define('VAR_TEXT_HTML', VAR_TEXT . CHAR_SLASH . VAR_HTML);
define('VAR_VAR_UNDER', CHAR_UNDER . VAR_VAR);
define('VAR_VAR_UNDER_END', CHAR_UNDER . VAR_VAR . CHAR_UNDER);
define('COCKPIT_YXORP', 'cockpit');
define('COCKPIT_ACCOUNTS', COCKPIT_YXORP . CHAR_SLASH . VAR_COCKPIT_ACCOUNTS);
define('COCKPIT_COLLECTIONS', 'collections');
define('COCKPIT_SITES', 'sites');
define('COCKPIT_HOST', 'host');
define('COCKPIT_TARGET', 'target');
define('DIR_ACTION', 'action' . DIRECTORY_SEPARATOR);
define('DIR_PARSER', 'parser' . DIRECTORY_SEPARATOR);
define('DIR_PLUGIN', 'plugin' . DIRECTORY_SEPARATOR);
define('DIR_OVERRIDE', 'override' . DIRECTORY_SEPARATOR);
define('DIR_GLOBAL', VAR_GLOBAL . DIRECTORY_SEPARATOR);
define('DIR_LIBLUDES', 'includes' . DIRECTORY_SEPARATOR);
define('DIR_INSTALL', 'install' . DIRECTORY_SEPARATOR);
define('DIR_COCKPIT', COCKPIT_YXORP . DIRECTORY_SEPARATOR);
define('DIR_ACCOUNTS', VAR_COCKPIT_ACCOUNTS . DIRECTORY_SEPARATOR);
define('DIR_VENDOR', 'vendor' . DIRECTORY_SEPARATOR);
define('DIR_APP', 'app' . DIRECTORY_SEPARATOR);
define('DIR_DATA', 'data' . DIRECTORY_SEPARATOR);
define('DIR_STORAGE', 'storage' . DIRECTORY_SEPARATOR);
define('DIR_HTTP', 'http' . DIRECTORY_SEPARATOR);
define('DIR_MINIFY', 'minify' . DIRECTORY_SEPARATOR);
define('DIR_BUGSNAG', 'snag' . DIRECTORY_SEPARATOR);
define('DIR_GUZZLE', 'proxy' . DIRECTORY_SEPARATOR);
define('DIR_PSR', 'psr' . DIRECTORY_SEPARATOR);
define('DIR_DEBUG', 'debug' . DIRECTORY_SEPARATOR);
define('EVENT_BUILD_CACHE', 'request' . CHAR_PERIOD . 'build_cached');
define('EVENT_BUILD_CONTEXT', 'request' . CHAR_PERIOD . 'build_context');
define('EVENT_BUILD_INCLUDES', 'request' . CHAR_PERIOD . 'build_includes');
define('EVENT_BUILD_HEADERS', 'request' . CHAR_PERIOD . 'build_headers');
define('EVENT_BUILD_REQUEST', 'request' . CHAR_PERIOD . 'build_request');
define('EVENT_BEFORE_SEND', 'request' . CHAR_PERIOD . 'before_send');
define('EVENT_SEND', 'request' . CHAR_PERIOD . 'send');
define('EVENT_SENT', 'request' . CHAR_PERIOD . 'sent');
define('EVENT_COMPLETE', 'request' . CHAR_PERIOD . 'complete');
define('EVENT_FINAL', 'request' . CHAR_PERIOD . 'final');
define('EVENT_EXCEPTION', 'request' . CHAR_PERIOD . 'build_exception');
define('EVENT_WRITE', 'curl' . CHAR_PERIOD . 'callback' . CHAR_PERIOD . 'write');
define('FILE_REWRITE', 'rewrite' . EXT_JSON);
define('FILE_INDEX', 'index' . EXT_PHP);
define('FILE_WRAPPER', 'wrapper' . EXT_PHP);
define('FILE_COCKPIT_BOOTSTRAP', 'bootstrap' . EXT_PHP);
define('FILE_MIME_TYPES', VAR_MIME . EXT_JSON);
define('FILE_GUZZLE', VAR_GUZZLE . EXT_PHAR);
define('FILE_BUGSNAG', VAR_BUGSNAG . EXT_PHAR);
define('FILE_TLDS_ALPHA_BY_DOMAIN', 'tlds-alpha-by-domain.txt');
define('FILE_PUBLIC_SUFFIX_LIST', 'public_suffix_list.dat');
define('SUBSCRIBE_METHOD', 'subscribe');
define('YXORP', 'yxorP');
define('YXORP_ACTIONS', 'YXORP_ACTIONS');
define('YXORP_EVENT_LIST', VAR_EVENT . CHAR_UNDER . VAR_LIST);
define('YXORP_MIME_TYPES', VAR_MIME . CHAR_UNDER . VAR_TYPES);
define('YXORP_REWRITE', VAR_INC . CHAR_UNDER . VAR_REWRITE);
define('YXORP_COCKPIT_INSTALL', VAR_COCKPIT . CHAR_UNDER . VAR_INSTALL);
define('YXORP_COCKPIT_APP', VAR_COCKPIT . CHAR_UNDER . VAR_APP);
define('YXORP_PHP_SELF', VAR_PHP . CHAR_UNDER . VAR_SELF);
define('YXORP_REQUEST_METHOD', VAR_REQUEST . CHAR_UNDER . VAR_METHOD);
define('YXORP_HTTP_', VAR_HTTPS_UP . CHAR_UNDER);
define('YXORP_REMOTE_ADDR', VAR_REMOTE . CHAR_UNDER . VAR_ADDR);
define('YXORP_TARGET_PLUGINS', 'TARGET_PLUGINS');
define('YXORP_GLOBAL_REPLACE', VAR_GLOBAL_UP . CHAR_UNDER . VAR_REPLACE);
define('YXORP_GLOBAL_PATTERN', VAR_GLOBAL_UP . CHAR_UNDER . VAR_PATTERN);
define('REG_ONE', CHAR_SLASH . CHAR_SLASH_BACK . CHAR_QUESTION . CHAR_PERIOD . CHAR_ASTRIX . CHAR_SLASH);
define('REG_TWO', CHAR_HASH . CHAR_PERIOD . CHAR_ASTRIX . CHAR_SLASH);
define('REG_THREE', CHAR_AT . CHAR_CURVE . CHAR_BRACKET . CHAR_SQUARE . CHAR_A . CHAR_DASH . CHAR_Z . CHAR_0 . CHAR_DASH . CHAR_9 . CHAR_UNDER . CHAR_SQUARE_CLOSE . CHAR_PLUS . CHAR_BRACKET_CLOSE . CHAR_CURVE_CLOSE . CHAR_AT . CHAR_S);
define('REG_FOUR', CHAR_SLASH_BACK . CHAR_ASTRIX);
define('REG_FIVE', CHAR_PERIOD . CHAR_ASTRIX);
define('REG_SIX', CHAR_SLASH_BACK . CHAR_QUESTION);
define('REG_SEVEN', CHAR_HASH . CHAR_UP);
define('REG_EIGHT', CHAR_HASH . CHAR_UP . VAR_HTTPS_ONLY . CHAR_QUESTION . CHAR_COLON . CHAR_HASH . CHAR_I);
define('REG_NINE', CHAR_HASH . CHAR_SLASH . CHAR_SQUARE . CHAR_UP . CHAR_SLASH . CHAR_SQUARE_CLOSE . CHAR_ASTRIX . CHAR_USD . CHAR_HASH);
define('REG_TEN', CHAR_HASH . CHAR_SLASH . CHAR_QUESTION . CHAR_EXCLAMATION . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_BRACKET_CLOSE . CHAR_SQUARE . CHAR_UP . CHAR_SLASH . CHAR_SQUARE_CLOSE . CHAR_PLUS . CHAR_SLASH . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_SLASH . CHAR_HASH);
define('REG_ELEVEN', CHAR_HASH . CHAR_BRACKET . CHAR_SLASH . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_QUESTION . CHAR_SLASH . CHAR_BRACKET_CLOSE . CHAR_HASH);
define('REG_TWELVE', CHAR_SLASH . CHAR_BRACKET . CHAR_QUESTION . CHAR_CAP_P . CHAR_ARROW . VAR_DOMAIN . CHAR_ARROW_CLOSE . CHAR_SQUARE . CHAR_A . CHAR_DASH . CHAR_Z . CHAR_0 . CHAR_DASH . CHAR_9 . CHAR_SQUARE_CLOSE . CHAR_SQUARE . CHAR_A . CHAR_DASH . CHAR_Z . CHAR_0 . CHAR_DASH . CHAR_9 . CHAR_SLASH_BACK . CHAR_DASH . CHAR_SQUARE_CLOSE . CHAR_CURVE . CHAR_1 . CHAR_COMMA . CHAR_6 . CHAR_3 . CHAR_CURVE_CLOSE . CHAR_SLASH_BACK . CHAR_PERIOD . CHAR_SQUARE . CHAR_A . CHAR_DASH . CHAR_Z . CHAR_PERIOD . CHAR_SQUARE_CLOSE . CHAR_CURVE . CHAR_2 . CHAR_COMMA . CHAR_6 . CHAR_CURVE_CLOSE . CHAR_BRACKET_CLOSE . CHAR_USD . CHAR_SLASH . CHAR_I);
define('ENV_ADMIN_USER', 'COCKPIT_USER' . EXT_ENV);
define('ENV_ADMIN_NAME', 'COCKPIT_NAME' . EXT_ENV);
define('ENV_ADMIN_EMAIL', 'COCKPIT_EMAIL' . EXT_ENV);
define('ENV_ADMIN_PASSWORD', 'COCKPIT_PASSWORD' . EXT_ENV);
define('ENV_GA_UTM', 'GA_UTM' . EXT_ENV);
define('ENV_BUGSNAG_KEY', 'BUGSNAG_KEY' . EXT_ENV);
define('ENV_DEBUG', 'DEBUG' . EXT_ENV);
define('ENV_DEFAULT_SITE', 'DEFAULT_SITE' . EXT_ENV);
define('ENV_DEFAULT_TARGET', 'DEFAULT_TARGET' . EXT_ENV);
define('RUNTIME_EXCEPTION', 'Directory "%s" was not created');
define('ACCESS_DENIED_EXCEPTION', 'Error: Access denied!');
define('ACCESS_ALREADY_DEFINED', 'Argument already exists and cannot be redefined!');
define('CACHE_EXPIRATION', @time() + (60 * 60 * 24 * 31 * 365));