#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    exit('Script needs to be run from Command Line Interface (cli)');
}

define('APP_CLI', true);

require __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;

$app = App::instance();
$cli = new Application("yxorP {$app['app.name']} Tower", $app['app.version']);

$app->trigger('app.cli.init', [$cli]);

$cli->run();