sudo rm -r ../app/tmp/
sudo mkdir -p ../app/tmp/
sudo chown root: ../app/tmp/
sudo chmod 777 ../app/tmp/
sudo chmod 777 ../app/lib/cockpit/storage/tmp
sudo chown root: ../app/lib/cockpit/storage/tmp
sudo chmod 777 ../app/lib/cockpit/storage/tmp
sudo chown root: ../app/lib/data/cookie_jar.text
sudo chmod 777 ../app/lib/data/cookie_jar.text
sudo tail -f /var/log/apache2/error.log
